Repository 2023GoogleSolutionChallenge/GDSC_Fooding, pull requests merged in 2023-03, with the labels that each got.

#5 Feat/#2 sign in&sign up UI
  public/src/css/sign-in.css
  public/src/css/sign-up-completed.css
  public/src/css/sign-up.css
  public/src/css/styleguide.css
  public/src/sign-in.html
  public/src/sign-up-completed.html
  public/src/sign-up.html
Labels: 🏗 Feat

#6 Feat/#4 mainpage UI
  public/src/assets/img4coreblock/checkmyorder.png
  public/src/assets/img4coreblock/location_icon.png
  public/src/assets/img4smbdy/img_hunger_1.png
  public/src/assets/img4smbdy/img_hunger_2.png
  public/src/assets/img4smbdy/img_hunger_3.png
  public/src/assets/img4smbdy/img_hunger_4.png
  public/src/css/mainpage.css
  public/src/css/setting.css
  public/src/css/styleguide.css
  public/src/mainpage.html
Labels: 🏗 Feat

#7 Feat/#3 pickup UI
  public/src/assets/back-button.png
  public/src/assets/back-button@2x.png
  public/src/assets/back-button@3x.png
  public/src/assets/menu-image.png
  public/src/assets/menu-image@2x.png
  public/src/assets/menu-image@3x.png
  public/src/css/pickup-location.css
  public/src/css/pickup-select.css
  public/src/css/styleguide.css
  public/src/pickup-location.html
  public/src/pickup-select.html
Labels: 🏗 Feat, 🖼 UI

#12 초기 배포 완료
  database.rules.json
  firebase.json
  firestore.indexes.json
  firestore.rules
  package-lock.json
  package.json
  public/404.html
  public/index.html
  public/src/css/mainpage.css
Labels: 📡 Network

#15 Feat/#8 mypage UI
  public/src/assets/Authorized_User.png
  public/src/assets/Authorized_User@2x.png
  public/src/assets/Authorized_User@3x.png
  public/src/css/mypage.css
  public/src/mypage.html
Labels: 🏗 Feat, 🖼 UI

#20 Feat/#18 index.html 창 구현 및 파이어베이스 일부 연동
  public/index.html
  public/src/css/index.css
  public/src/css/sign-up-completed.css
  public/src/css/styleguide.css
  public/src/sign-up-completed.html
Labels: 📡 Network, 🖼 UI

#22 Feat/#16 user authentication
  public/index.html
  public/src/sign-in.html
  public/src/sign-up.html
Labels: ✅ Chore, 🏗 Feat

#24 Chore/#19 make connection network
  public/src/check-myorder.html
  public/src/css/setting.css
  public/src/mainpage.html
  public/src/mypage.html
  public/src/pickup-completed.html
  public/src/pickup-select.html
  public/src/scan-qr.html
Labels: 📡 Network

#26 Feat/#21 checkmyorder UI
  public/src/assets/scan_qr.png
  public/src/assets/scan_qr@2x.png
  public/src/assets/scan_qr@3x.png
  public/src/check-myorder.html
  public/src/css/check-myorder.css
Labels: 🏗 Feat, 🖼 UI

#25 Chore/#23-로그인, 회원가입 페이지 input 위치 조정 완료
  public/src/css/index.css
  public/src/css/sign-up.css
Labels: ✅ Chore

#29 Fix/#28 메인페이지로 redirect network
  public/src/check-myorder.html
  public/src/mypage.html
  public/src/pickup-completed.html
  public/src/scan-qr.html
Labels: ✅ Chore

#30 Chore/#27 modify UI
  public/src/css/mainpage.css
  public/src/css/mypage.css
  public/src/mypage.html
  public/src/pickup-select.html
  public/src/sign-up.html
Labels: ✅ Chore
